
 INSERT INTO cuentas (ID,COD_cuentas,NOMBRE)VALUES('1','100','SERVICIOS');



 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('1','1','100.1','AGUA');



 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('1','2','100.2','INTERNET');



 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('1','3','100.3','LUZ');



 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('1','4','100.4','TELEFONO');




 INSERT INTO cuentas (ID,COD_cuentas,NOMBRE)VALUES('2','200','GASTOS DE ALIMENTACION');



 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('2','5','200.1','ALIMENTACION');



 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('2','6','200.2','FESTIVIDADES ESPECIALES');



 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('2','7','200.3','REFRIGERIO DOMINGOS');




 INSERT INTO cuentas (ID,COD_cuentas,NOMBRE)VALUES('3','300','SUELDOS SALARIOS Y BENEFICIOS');



 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('3','8','300.1','BENEFICIOS SOCIALES');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('3','9','300.2','SUELDO ADMINISTRATIVO');



 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('3','10','300.3','SUELDO APOYO');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('3','11','300.4','SUELDO EJECUTIVO');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('3','12','300.5','SUELDO TECNICO');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('3','13','300.6','SUELDO COCINA Y ALMACEN');



 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('3','14','300.7','SALARIO PROFESORES EXTERNOS');



 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('3','15','300.8','REEMPLAZOS');



 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('3','16','300.9','SALARIO ADESTAJO');



 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('3','17','300.10','BONOS EXTRAORDINARIOS');



 INSERT INTO cuentas (ID,COD_cuentas,NOMBRE)VALUES('4','400','GASTOS EDUCACION');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('4','18','400.1','ALMUERZOS ESCOLARES');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('4','19','400.2','BECAS UNIVERSITARIAS');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('4','20','400.3','CORTE DE PELO');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('4','21','400.4','FOTOCOPIAS');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('4','22','400.5','LIBROS');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('4','23','400.6','MANTENIMIENTO COMPUTADORAS');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('4','24','400.7','MATERIAL ESCOLAR EXTRA');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('4','25','400.8','MATERIAL TRABAJO');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('4','26','400.9','MENSUALIDADES Y CUOTAS');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('4','27','400.10','MISCELANEOS ESCOLARES');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('4','28','400.11','PASAJES ESCOLARES');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('4','29','400.12','RECREOS');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('4','30','400.13','COSTURA DE ZAPATOS');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('4','31','400.14','TRABAJOS PRACTICOS');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('4','32','400.15','VESTIMENTA ESCOLAR');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('4','33','400.16','CURSOS EXTERNOS');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('4','34','400.17','CAMPAMENTOS');



 INSERT INTO cuentas (ID,COD_cuentas,NOMBRE)VALUES('5','500','GASTOS DE SALUD');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('5','35','500.1','ATENCION MEDICA');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('5','36','500.2','ATENCION ESPECIALIDADES');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('5','37','500.3','CIRUGIAS');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('5','38','500.4','LABORATORIOS');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('5','39','500.5','MEDICAMENTOS');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('5','40','500.6','EXAMENES MEDICOS');



 INSERT INTO cuentas (ID,COD_cuentas,NOMBRE)VALUES('6','600','GASTOS VEHICULO');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('6','41','600.1','MANTENIMIENTO VEHICULO');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('6','42','600.2','REPARACION');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('6','43','600.3','COMPRA MATERIAL');



 INSERT INTO cuentas (ID,COD_cuentas,NOMBRE)VALUES('7','700','GASTOS TRANSPORTE');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('7','44','700.1','COMBUSTIBLE');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('7','45','700.2','CONSUMO GAS');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('7','46','700.3','PASAJES RESIDENTES EXTRAS');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('7','47','700.4','PASAJES PERSONAL');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('7','48','700.5','CONTRATOS ADICIONALES TRANSPORTE');



 INSERT INTO cuentas (ID,COD_cuentas,NOMBRE)VALUES('8','800','GASTOS VARIOS');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('8','49','800.1','MATERIAL ESCRITORIO');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('8','50','800.2','MATERIAL LIMPIEZA');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('8','51','800.3','MATERIAL DE MANTENIMIENTO');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('8','52','800.4','REP. MANT. INSTALACIONES');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('8','53','800.5','GASTOS COMUNICACION');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('8','54','800.6','MISCELANEOS');



 INSERT INTO cuentas (ID,COD_cuentas,NOMBRE)VALUES('9','900','GASTOS INSTRUCCION MILITAR');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('9','55','900.1','ALIMENTACION CUARTEL');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('9','56','900.2','CUOTAS');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('9','57','900.3','INSCRIPCION');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('9','58','900.4','MATERIALES');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('9','59','900.5','MISCELANEOS CUARTEL');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('9','60','900.6','TRANSPORTE');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('9','61','900.7','VESTIMENTA');



 INSERT INTO cuentas (ID,COD_cuentas,NOMBRE)VALUES('10','1000','GASTOS AGRICULTURA');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('10','62','1000.1','INSUMOS');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('10','63','1000.2','JORNALES');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('10','64','1000.3','TRACTOR');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('10','65','1000.4','VENTA PRODUCTO');



 INSERT INTO cuentas (ID,COD_cuentas,NOMBRE)VALUES('11','1100','GASTOS CONSTRUCCION');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('11','66','1100.1','ENTREGA EN EFECTIVO');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('11','67','1100.2','MATERIAL CONSTRUCCION');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('11','68','1100.3','MANO DE OBRA CONST');



 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('11','69','1100.4','MISCELANEOS CONSTRUCCION');



 INSERT INTO cuentas (ID,COD_cuentas,NOMBRE)VALUES('12','1200','MANTENIMIMENTO INSTALACIONES');



 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('12','70','1200.1','MATERIAL MANTENIMIENTO INST');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('12','71','1200.2','MANO DE OBRA');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('12','72','1200.3','SERVICIOS');



 INSERT INTO cuentas (ID,COD_cuentas,NOMBRE)VALUES('13','1300','BANCOS');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('13','73','1300.1','COMISION GIRO BANCARIO');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('13','74','1300.2','CARGO USO DE ATM');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('13','75','1300.3','DIFERENCIA POR UTILIZACION DE EFECTIVO');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('13','76','1300.4','INTERESES');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('13','77','1300.5','MANTENIMIENTO TARJETA');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('13','78','1300.6','PAGO ITF');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('13','79','1300.7','RC-IVA');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('13','80','1300.8','MISCELANEOS BANCO');



 INSERT INTO cuentas (ID,COD_cuentas,NOMBRE)VALUES('14','1400','GASTOS DE VESTIMENTA');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('14','81','1400.1','UNIFORMES ESCOLARES');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('14','82','1400.2','ROPA DE VESTIR');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('14','83','1400.3','ROPA INTERIOR');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('14','84','1400.4','ZAPATOS');



 INSERT INTO cuentas (ID,COD_cuentas,NOMBRE)VALUES('15','1500','ADQUISICION DE ACTIVOS');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('15','85','1500.1','ELECTRONICOS');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('15','86','1500.2','ELECTRICOS');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('15','87','1500.3','MUEBLES');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('15','88','1500.4','TERRENOS');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('15','89','1500.5','MOVILIDADES');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('15','90','1500.6','HERRAMIENTAS');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('15','91','1500.7','MISCELANEOS ACTIVOS');



 INSERT INTO cuentas (ID,COD_cuentas,NOMBRE)VALUES('16','1600','TRASPASOS ROSA DE SARON');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('16','92','1600.1','TRASPASOS ROSA DE SARON');



 INSERT INTO cuentas (ID,COD_cuentas,NOMBRE)VALUES('17','1700','PAGO DE IMPUESTOS');



 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('17','93','1700.1','INMUEBLES');



 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('17','94','1700.2','AUTOMOVILES');



 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('17','95','1700.3','RC-IVA');



 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('17','96','1700.4','IT');



 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('17','97','1700.5','IMPUESTOS VARIOS');



 INSERT INTO cuentas (ID,COD_cuentas,NOMBRE)VALUES('18','1800','ASIENTOS DE AJUSTE');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('18','98','1800.1','REDEPOSITOS');



 INSERT INTO cuentas (ID,COD_cuentas,NOMBRE)VALUES('19','1900','BONOS EXTRAORDINARIAS');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('19','99','1900.1','SUBSIDIO PRE-NATAL');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('19','100','1900.2','BONO NATALIDAD');


 INSERT INTO sub_cuentas(CUENTA_ID,ID,COD_sub_cuentas,NOMBRE)VALUES('19','101','1900.3','SUBSIDIO LACTANCIA');


