
              INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('1','1','Cercado');
    		  INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('2','1','Vaca Diez');
    		  INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('3','1','Josè Ballivian');
    		  INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('4','1','Yacuma');
    		  INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('5','1','Moxos');
    		  INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('6','1','Marban');
    		  INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('7','1','Mamoré');
    		  INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('8','1','Itenez');
    		  INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('9','2','Oropeza');
    		  INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('10','2','Azurduy');
    		  INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('11','2','Zudañez');
    		  INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('12','2','Tomina');
			  INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('13','2','Hernando Siles');
			  INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('14','2','Yamparaez');
			  INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('15','2','Nor Cinti');
			  INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('16','2','Sur Cinti');
			  INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('17','2','Belisario Boeto');
			  INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('18','2','Luis Calvo');
			  INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('19','3','Cercado');
			  INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('20','3','Campero');
			  INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('21','3','Ayopaya');
			  INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('22','3','Esteban Arce');
			  INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('23','3','Arani');
			  INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('24','3','Arque');
			  INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('25','3','Capinota');
			  INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('26','3','Germán Jordan');
			  INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('27','3','Quillacollo');
			  INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('28','3','Chapare');
			  INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('29','3','Tapacarí');
			  INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('30','3','Carrasco');
			  INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('31','3','Mizque');
			  INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('32','3','Punata');
			  INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('33','3','Bolivar');
			  INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('34','3','Tiraque');
			  INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('35','4','Murillo');
			  INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('36','4','Omasuyos');
			  INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('37','4','Pacajes');
			  INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('38','4','Camacho');
			  INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('39','4','Muñecas');
			  INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('40','4','Larecaja');
			  INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('41','4','Franz Tamayo');
			  INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('42','4','Ingavi');
			  INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('43','4','Loayza');
			  INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('44','4','Inquisivi');
			  INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('45','4','Nor Yungas');
			  INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('46','4','Sud Yungas');
			  INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('47','4','Los Andes');
			  INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('48','4','Aroma');
			  INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('49','4','Nor Yungas');
			  INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('50','4','Larecaja');
			  INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('51','4','Abel Iturraled');
			  INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('52','4','Bautista Saavedra');
			  INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('53','4','Manco Kapac');
			  INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('54','4','Gualberto Villarroel');
			  INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('55','4','José Manuel Pando');
			  INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('56','4','Caranavi');
			  INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('57','5','Cercado');
			  INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('58','5','Eduardo Avaroa');
			  INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('59','5','Carangas');
			  INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('60','5','Sajama');
			  INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('61','5','Litoral');
			  INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('62','5','Poopo');
			  INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('63','5','Pantaleón Dalence');
			  INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('64','5','Ladislao Cabrera');
			  INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('65','5','Atahuallpa');
			  INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('66','5','Saucari');
			  INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('67','5','Tomas Barrón');
			  INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('68','5','Nor Carangas');
			  INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('69','5','Sud Carangas');
			  INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('70','5','San Pedro de Totora');
              INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('71','5','Sebastian Pagador');
              INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('72','5','Puerto de Mejillones');
              INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('73','6','Nicolas Suarez');
              INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('74','6','Manuripi');
              INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('75','6','Madre de Dios');
              INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('76','6','Abuná');
              INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('77','6','Fedrico Román');
              INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('78','7','Tomás Frías');
              INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('79','7','Rafael Bustillo');
              INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('80','7','Cornelio Saavedra');
              INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('81','7','Chayanta');
              INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('82','7','Charcas');
              INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('83','7','Nor Chichas');
              INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('84','7','Sud Chichas');
              INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('85','7','Alonso de Ibañez');
              INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('86','7','Nor Lipez');
              INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('87','7','Sud Lipez');
              INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('88','7','Josè María Linares');
              INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('89','7','Antonio Quijarro');
              INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('90','7','Bernardino Bilbao');
              INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('91','7','Daniel Campos');
              INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('92','7','Modesto Omiste');
              INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('93','7','Enrique Baldivieso');
              INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('94','8','Andres Ibañez');
              INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('95','8','Ignacio Warnes');
              INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('96','8','José Miguel de Velasco');
              INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('97','8','Ichilo');
              INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('98','8','Chiquitos');
              INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('99','8','Sara');
              INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('100','8','Cordillera');
              INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('101','8','Vallegrande');
              INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('102','8','Florida');
              INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('103','8','Obispo Santiestevan');
              INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('104','8','Ñuflo de Chavez');
              INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('105','8','Angel Sandoval');
              INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('106','8','Manuel María Caballero');
              INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('107','8','Germán Busch');
              INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('108','8','Guarayos');
              INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('109','9','Cercado');
              INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('110','9','Aniceto Arce');
              INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('111','9','Gran Chaco');
              INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('112','9','Avilés');
              INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('113','9','Mendez');
              INSERT INTO provincias (ID,CIUDAD_ID,NOMBRE) VALUES('114','9','Burnet O Connor');






