INSERT INTO tallas (ID,NOMBRE) VALUES('1','XS');
INSERT INTO tallas (ID,NOMBRE) VALUES('2','S');
INSERT INTO tallas (ID,NOMBRE) VALUES('3','M');
INSERT INTO tallas (ID,NOMBRE) VALUES('4','L');
INSERT INTO tallas (ID,NOMBRE) VALUES('5','XL');
INSERT INTO tallas (ID,NOMBRE) VALUES('6','XXL');
INSERT INTO tallas (ID,NOMBRE) VALUES('7','XXXL');

INSERT INTO tallas (ID,NOMBRE) VALUES('8','28');
INSERT INTO tallas (ID,NOMBRE) VALUES('9','30');
INSERT INTO tallas (ID,NOMBRE) VALUES('10','32');
INSERT INTO tallas (ID,NOMBRE) VALUES('11','34');
INSERT INTO tallas (ID,NOMBRE) VALUES('12','36');
INSERT INTO tallas (ID,NOMBRE) VALUES('13','38');
INSERT INTO tallas (ID,NOMBRE) VALUES('14','40');
INSERT INTO tallas (ID,NOMBRE) VALUES('15','42');
INSERT INTO tallas (ID,NOMBRE) VALUES('16','44');
INSERT INTO tallas (ID,NOMBRE) VALUES('17','46');

INSERT INTO tallas (ID,NOMBRE) VALUES('18','Única');

-- TALLAS INFANTILES (desde 4 años en adelante)
INSERT INTO tallas (ID,NOMBRE) VALUES('19','4 años');
INSERT INTO tallas (ID,NOMBRE) VALUES('20','6 años');
INSERT INTO tallas (ID,NOMBRE) VALUES('21','8 años');
INSERT INTO tallas (ID,NOMBRE) VALUES('22','10 años');
INSERT INTO tallas (ID,NOMBRE) VALUES('23','12 años');
INSERT INTO tallas (ID,NOMBRE) VALUES('24','14 años');
INSERT INTO tallas (ID,NOMBRE) VALUES('25','16 años');

			 
              


